Update azuure.yml

diff --git a/.github/workflows/azuure.yml b/.github/workflows/azuure.yml
--- a/.github/workflows/azuure.yml
+++ b/.github/workflows/azuure.yml
@@ -100,3 +100,35 @@ jobs:
         run: |
           echo "::set-output name=deploy::$(if [ ${{ github.event_name }} == 'push' ] && [ ${{ github.ref }} == 'refs/heads/main' ]; then echo 'true'; elif [ ${{ github.event_name }} == 'push' ] && [[ "${{ github.ref }}" =~ refs/tags/${{ env.GIT_TAG_REGEX_STRING }} ]]; then echo 'true'; elif [ ${{ github.event_name }} == 'workflow_run' ] && [ ${{ github.event.workflow_run.event == 'push' }} ] && [ ${{ github.event.workflow_run.head_branch }} == 'main' ]; then echo 'true'; elif [ ${{ github.event_name }} == 'workflow_run' ] && [ ${{ github.event.workflow_run.event == 'push' }} ] && [[ "${{ github.event.workflow_run.head_branch }}" =~ refs/tags/${{ env.GIT_TAG_REGEX_STRING }} ]]; then echo 'true'; elif [ ${{ github.event_name }} == 'workflow_run' ] && [ ${{ github.event.workflow_run.event == 'manual' }} ] && [ ${{ github.event.workflow_run.conclusion }} == 'success' ]; then echo 'true'; elif [ ${{ github.event_name }} == 'workflow_run' ] && [ ${{ github.event.workflow_run.event == 'schedule' }} ] && [ ${{ github.event.workflow_run.conclusion }} == 'success' ]; then echo 'true'; elif [ ${{ github.event_name }} == 'workflow_run' ] && [ ${{ github.event.workflow_run.event == 'workflow_dispatch' }} ] && [ ${{ github.event.workflow_run.conclusion }} == 'success' ]; then echo 'true'; else echo 'false'; fi)"
 
+      - name: JAR deployment (non-prod)
+        if: |
+          github.event_name == 'push' &&
+          (
+            github.ref == 'refs/heads/${{ env.MAIN_BRANCH_NAME }}' ||
+            startsWith(github.ref, 'refs/tags/') && contains(github.ref, env.GIT_TAG_REGEX_STRING) ||
+            env.FORCE_DEPLOY_CLOUD == 'true'
+          )
+        run: |
+          echo "Deploying JAR (non-prod)"
+          
+          # Adding retry logic with a bash loop
+          retry_count=3
+          retry_delay=10
+          until [ $retry_count -le 0 ]; do
+            echo "Running azcopyExecstaticstorage, attempts left: $retry_count"
+            
+            docker run --rm -v $(pwd):/workspace -w /workspace docker-terraform-slave bash -c 'azcopyExecstaticstorage'
+            
+            # Check if the command was successful
+            if [ $? -eq 0 ]; then
+              echo "Deployment successful!"
+              break
+            else
+              echo "Deployment failed. Retrying in $retry_delay seconds..."
+              sleep $retry_delay
+              retry_count=$((retry_count-1))
+            fi
+          done
+       with:
+         inputs:
+           force-deploy-cloud: ${{ github.event.inputs.force-deploy-cloud }}
